name: Build Docker Images

on:
  push

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Build and push windows image
        env: 
          USER: ${{ secrets.DOCKER_USER }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        working-directory: .
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -f ue-win.dockerfile -m 6G -t $env:USER/ue-win:latest .
          docker push $env:USER/ue-win:latest
          docker logout